using DevExpress.XtraEditors;
using StorgeSysm.Frm_addS;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace StorgeSysm.Forms_ui
{
    public partial class colect_part : DevExpress.XtraEditors.XtraUserControl
    {
        Parts add;
        public int id;
        public int id2;
        SyStorgeDataEntities db;
       
        public colect_part()
        {
            InitializeComponent();
            LoadData1();
             LoadData2();
        }
        public void LoadData1()


        {



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            StorgeSysm.SyStorgeDataEntities dbContext = new StorgeSysm.SyStorgeDataEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.Parts.LoadAsync().ContinueWith(loadTask =>
            {

                gridControl1.DataSource = dbContext.Parts.Local.ToBindingList();

            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());



        }
        public void LoadData2()


        {



            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            StorgeSysm.SyStorgeDataEntities dbContext = new StorgeSysm.SyStorgeDataEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.

            dbContext.View.LoadAsync().ContinueWith(loadTask =>
            {

                gridControl2.DataSource = dbContext.View.Local.ToBindingList();

            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());


        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            try
            {
                Form_AddP page = new Form_AddP();
                page.btn_add.Text = "اضافة";
                page.btn_addclose.Text = "اضافة + غلق";
                page.edt_name_p.Text = "";
                page.id = 0;
                page.page = this;
                page.Show();
            }
            catch { MessageBox.Show("خطأ غير متوقع"); }
        }

        private void btn_edit_Click(object sender, EventArgs e)
        {
            try
            {
                db = new SyStorgeDataEntities();
                add = new Parts();
                STORAGE asa = new STORAGE();
                id = Convert.ToInt16(gridView2.GetFocusedRowCellValue("Id"));
                if (id != 0)
                {
                    add = db.Parts.Where(x => x.Id == id).FirstOrDefault();
                    asa = db.STORAGE.Where(x => x.Id == add.storge_id ).FirstOrDefault();
                    Form_AddP page = new Form_AddP();
                    page.btn_add.Text = "تعديل";
                    page.btn_addclose.Text = "تعديل + غلق";
                    page.edt_name_p.Text = add.Part_Name;
               // page.comboBox_unit.Text = add.Unit;
                    page.comboBox_s.SelectedItem = asa.StoreName;
                    page.id = id;
                    page.page = this;
                    page.Show();
                }
                else
                {
                    MessageBox.Show("لا يوجد بيانات لتعديلها, اختر صف لتعديله", "لا يمكن اجراء العملية", MessageBoxButtons.OK, MessageBoxIcon.Information);

                }


            }
            catch
            {
                MessageBox.Show("خطأ في الاتصال بقاعدة البيانات", "خطأ في الاتصال", MessageBoxButtons.OK, MessageBoxIcon.Information);

            }
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            try
            {
                db = new SyStorgeDataEntities();
                add = new Parts();
                id2 = Convert.ToInt16(gridView2.GetFocusedRowCellValue("Id"));
                if (id2 != 0)
                {
                    var dilogeresult = MessageBox.Show("هل انت متأكد من هذا الاجراء , لا يمكن استرجاع البيانات , سيتم حذف جميع البيانات المرتبطة", "اجراء حذف", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
                    if (dilogeresult == DialogResult.Yes)
                    {
                        add = db.Parts.Where(x => x.Id == id2).FirstOrDefault();
                        db.Entry(add).State = System.Data.Entity.EntityState.Deleted;
                        db.SaveChanges();
                        LoadData1();



                    }

                }
                else
                {
                    MessageBox.Show("لا يوجد بيانات لحذفها", "لا يمكن اجراء العملية", MessageBoxButtons.OK, MessageBoxIcon.Warning,
                 MessageBoxDefaultButton.Button1,
                 MessageBoxOptions.RightAlign | MessageBoxOptions.RtlReading);

                }


            }
            catch(Exception ex)
            {
                MessageBox.Show("خطأ في الاتصال بقاعدة البيانات"+ ex, "خطأ في الاتصال", MessageBoxButtons.OK, MessageBoxIcon.Information);

            }
        }

        private void btn_update_Click(object sender, EventArgs e)
        {
            LoadData1();
        
        }

        private void btn_print_Click(object sender, EventArgs e)
        {
          

                gridControl1.ShowPrintPreview();
      
           

        }









        private void colect_part_Load(object sender, EventArgs e)
        {
            LoadData2();
            LoadData1();
          
        }

 

        private void simpleButton1_Click(object sender, EventArgs e)
        {
            gridControl2.ShowPrintPreview();
        }

        private void simpleButton2_Click(object sender, EventArgs e)
        {
            LoadData2();
        }

        private void btn_add_Click_1(object sender, EventArgs e)
        {

        }

        private void tabNavigationPage1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gridControl2_Click(object sender, EventArgs e)
        {

        }

        private void panelControl1_Paint(object sender, PaintEventArgs e)
        {

        }

        private void tabNavigationPage2_Paint(object sender, PaintEventArgs e)
        {

        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        private void panelControl3_Paint(object sender, PaintEventArgs e)
        {

        }

        private void tabPane1_Click(object sender, EventArgs e)
        {

        }
    }
    }  
    

