//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorgeSysm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compart
    {
        public int Id { get; set; }
        public Nullable<int> Id_coms { get; set; }
        public Nullable<int> Id_part { get; set; }
        public Nullable<int> Add_parts { get; set; }
        public Nullable<int> Id_typ { get; set; }
        public Nullable<double> Add_one { get; set; }
        public Nullable<double> Other_pri { get; set; }
        public Nullable<double> price_mins { get; set; }
        public Nullable<double> Add_all { get; set; }
        public string Num_mars { get; set; }
        public Nullable<int> Id_unit { get; set; }
        public string Nots { get; set; }
    
        public virtual Parts Parts { get; set; }
        public virtual Incoming Incoming { get; set; }
        public virtual Type_Price Type_Price { get; set; }
        public virtual Units Units { get; set; }
    }
}
