//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorgeSysm
{
    using System;
    using System.Collections.Generic;
    
    public partial class Outsale
    {
        public int Id { get; set; }
        public Nullable<int> Id_cost { get; set; }
        public Nullable<int> Id_Part { get; set; }
        public Nullable<int> Id_Unit { get; set; }
        public Nullable<int> Qut_sell { get; set; }
        public Nullable<double> Sell_price { get; set; }
        public Nullable<double> Sell_all_price { get; set; }
        public Nullable<double> Sell_price_min { get; set; }
        public Nullable<int> Id_typ { get; set; }
        public Nullable<double> Other_pr { get; set; }
        public string Nots { get; set; }
    
        public virtual Coustmer Coustmer { get; set; }
        public virtual Parts Parts { get; set; }
        public virtual Type_Price Type_Price { get; set; }
        public virtual Units Units { get; set; }
    }
}
