//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StorgeSysm
{
    using System;
    using System.Collections.Generic;
    
    public partial class View
    {
        public int Id { get; set; }
        public string Part_Name { get; set; }
        public string unit_name { get; set; }
        public int Allbuy { get; set; }
        public double AllbuyPrice { get; set; }
        public Nullable<int> Total_Parts { get; set; }
        public Nullable<double> Total_Pris { get; set; }
        public int Allsell { get; set; }
        public double AllsellPrice { get; set; }
        public string StoreName { get; set; }
    }
}
